language: node_js
node_js:
  - "lts/*"
services:
  - postgresql
before_script:
  - psql -U postgres -c "create database timecloud;"
  - node_modules/.bin/sequelize db:migrate --url "postgres://postgres:@localhost/timecloud"
  - psql -U postgres -d timecloud -c "select * from \"Clients\";"
